### ISSUE TITLE
fluentd metrics are not shown on Prometheus

### ISSUE THREAD

**Issue by socialfeels** [kazegusuri/fluent-plugin-prometheus#28] opened 2017-06-13 11:55 UTC
Hello kazegusuri, 
I am trying to run fluent-plugin-prometheus on k8s,  I see fluentd pod on k8s targets, It is up. but I couldn't see any metrics related **docker_command_log** to execute on prometheus. Please, can you help this issue?
Please find my files in below.

Thanks, 

Dockerfile:
```
FROM fluent/fluentd:v0.12-onbuild

USER root

RUN apk add --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install \
        fluent-plugin-rewrite-tag-filter:1.5.6 \
        fluent-plugin-parser:0.6.1 \
        fluent-plugin-prometheus:0.3.0 \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem

# listen port 24224 for Fluentd forward protocol
EXPOSE 24224
# prometheus plugin expose metrics at 0.0.0.0:24231/metrics
EXPOSE 24231
```
fluent.conf
```
<source>
  @type forward
</source>
<source>
  @type prometheus
</source>

<filter docker.**>
  @type prometheus
  <metric>
    name docker_command_log
    type counter
    desc total docker commands
    #key log
  </metric>
</filter>

<match docker.**>
  @type copy
  <store>
    @type stdout
  </store>
</match>
```
k8s-development.yaml

```
...
apiVersion: v1
kind: Deployment
metadata:
  name: fluentd
spec:
  template:
    metadata:
      labels:
        app: fluentd
      name: fluentd
    spec:
      containers:
      - image: myimage
        name: fluentd
        ports:
        - containerPort: 24231
          hostPort: 24231
```
prometheus.yml
```
...
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
         - targets: ['localhost:9090','fluentd:24231']
```

**Comment by anupamkamal01** [comment] 2017-06-28 17:49
Hi , you have not specified the input / source . 
You may refer this ===> http://docs.fluentd.org/v0.12/articles/input-plugin-overview

Thanks 
Anupam

**Comment by kazegusuri** [comment] 2017-07-01 16:50
Thank you for very detailed report.
I tried to reproduce the issue with you configuration and dockerfile, but it works fine.
Judging from your fluent.conf, do you refer this [blog post](https://blog.treasuredata.com/blog/2016/07/19/routing-data-from-docker-to-prometheus-server-via-fluentd/) right?
In the post,  run following command to run a docker container: (wrong)
```
sudo docker run -ti --name test --log-driver=fluentd ubuntu /bin/bash
```

The command may start container successfully and the logs are sent to Fluentd, but the message tag is different from one of that time.


Now we need to specify fluentd tag in the command-line: (right)
```
sudo docker run -ti --name test --log-driver=fluentd --log-opt tag="docker.{{.ID}}" ubuntu /bin/bash
```

Without `--logopt`, Fluentd receives invalid tag from other containers then logs something like this:
```
2017-07-01 16:33:41 +0000 [warn]: no patterns matched tag="347176804a85"
```

**Comment by socialfeels** [comment] 2017-07-06 12:35
Thank you for the reply. Yes, I referred the blog, but I don't use the command to run a Docker container. I use k8s. I mentioned above (k8s-development.yaml). My actual problem is related Prometheus metric. I couldn't see docker_command_log metric.  Please find the screenshot in below. 
<img width="447" alt="prometheus" src="https://user-images.githubusercontent.com/15929049/27911137-a58c2156-6260-11e7-84e7-5e811dc30287.png">

**Comment by kazegusuri** [comment] 2017-07-07 13:31
Hmm, I don't have a k8s environment to confirm that.
I want to know with what **tag** each containers send logs to fluentd. Could you test with following config and run some command inside container on k8s?

```
<match **>
  @type stdout
</match>
```

**Comment by kazegusuri** [comment] 2017-07-28 14:38
I close this issue because not updated.
Please feel free to reopen if you have a update or comment.

**Closed by kazegusuri** 2017-07-28 14:38 UTC
